site_name: BlurEngine
use_directory_urls: false
markdown_extensions:
    - pymdownx.superfences
    - admonition
    - pymdownx.details
plugins:
    - search
    - localsearch
nav:
    - "Introduction": index.md
    - "General Reference":
        - "Events": events.md
        - "Classes": classes.md
        - "Enums": enums.md
        - "Global Functions": functions.md

    - "Libraries": 
        - "index": libraries/libraries.md
        - "BLF": libraries/blf.md
        - "event": libraries/event.md
        - "GUI": libraries/gui.md
        - "debug": libraries/debug.md
        - "mouse": libraries/mouse.md

    #- "Guides": 
    - "Contribute": "https://github.com/Functionable/BlurEngineLuaDocs"
theme:
    features:
        - navigation.tabs
    name: material
    icon:
        logo: images/logo
    custom_dir: theme
