site_name: BlurEngine
use_directory_urls: false
plugins:
    - search
    - localsearch
nav:
    - "Introduction": index.md
    - "General Reference":
        - "Events": events.md
        - "Classes": classes.md
        - "Enums": enums.md
        - "Global Functions": functions.md
        - "Libraries": libraries/libraries.md
    #- "Guides": 
    - "Contribute to this wiki": "https://github.com/Functionable/BlurEngineLuaDocs"
theme:
    name: material
    icon:
        logo: images/logo
    custom_dir: theme
